import {BALANCE,ITEMS,evaluate,levelFor,comboKey,makeRound} from './engine.js';
const $=s=>document.querySelector(s), SAVE='jugaad-junction-v1';
let storageOK=true;let saved;try{saved=JSON.parse(localStorage.getItem(SAVE)||'{}')}catch{saved={};storageOK=false}
let discoveries=Array.isArray(saved.discoveries)?saved.discoveries:[], best=Number(saved.best)||0;
let settings={sound:true,motion:!matchMedia('(prefers-reduced-motion: reduce)').matches,...saved.settings};
let run=null,job=null,selected=[],remaining=42,phase='menu',paused=false,returnScreen=null,audio=null,last=performance.now();
function persist(){try{localStorage.setItem(SAVE,JSON.stringify({discoveries,best,settings,run,job,selected,remaining,phase:phase==='result'?'between':phase}));}catch{storageOK=false;toast('Browser storage is unavailable. This session still works.')}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function sound(type){if(!settings.sound)return;try{audio??=new AudioContext();audio.resume();const patterns={click:[360],clang:[210,520],success:[392,494,587,784],fail:[180,130,80],spark:[900,110,1400],coins:[880,1175],arrival:[440,660],level:[523,659,784,1047]};(patterns[type]||patterns.click).forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type=['clang','spark','fail'].includes(type)?'triangle':'sine';o.frequency.setValueAtTime(f,audio.currentTime+i*.09);g.gain.setValueAtTime(0,audio.currentTime+i*.09);g.gain.linearRampToValueAtTime(.075,audio.currentTime+i*.09+.008);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+i*.09+.18);o.connect(g).connect(audio.destination);o.start(audio.currentTime+i*.09);o.stop(audio.currentTime+i*.09+.2)})}catch{}}
const shapes={
 battery:'<rect x="17" y="11" width="30" height="43" rx="5" fill="#859d77"/><path d="M25 11V6h14v5M27 24h10m-5-5v10M27 43h10"/>',
 brick:'<path d="M8 24L42 14l16 10-34 12z" fill="#c77b51"/><path d="M8 24v20l16 10V36m0 18 34-12V24" fill="#b56848"/><path d="m24 36 34-12M25 30l16-6"/>',
 bottle:'<path d="M26 6h12v13l7 9v24q0 6-7 6H26q-7 0-7-6V28l7-9z" fill="#9cbdb0"/><path d="M26 11h12M20 35h24v14H20" fill="#e2c26f"/>',
 wire:'<path d="M9 18q42-17 42 9T18 45q-15-2-7-11t24 5" stroke="#cc6c46" stroke-width="6" fill="none"/><path d="m6 17 6-1m23 23 9 4" stroke-width="4"/>',
 tape:'<ellipse cx="32" cy="28" rx="24" ry="20" fill="#a2a396"/><path d="M8 28v13q25 28 48 0V28" fill="#8d9489"/><ellipse cx="32" cy="28" rx="12" ry="10" fill="#eae4cd"/>',
 ring:'<circle cx="32" cy="32" r="23" fill="#5c6960"/><circle cx="32" cy="32" r="14" fill="#eee7d3"/><path d="m12 18 7 3m24 25 6 3M15 44l5-4m25-23-6 5"/>',
 fan:'<circle cx="32" cy="32" r="25" fill="#c3cdb8"/><path d="M32 32Q7 5 30 9q13 2 2 23Q61 7 55 30q-3 12-23 2Q55 57 34 56q-12-1-2-24Q3 56 9 33q3-12 23-1" fill="#5c8c80"/><circle cx="32" cy="32" r="5" fill="#e2bb61"/>',
 pipe:'<path d="M11 15h18v21h22v17H21q-10 0-10-10z" fill="#c1c6ae"/><path d="M10 15h20M51 35v19M8 23h23M43 34v21"/>',
 motor:'<rect x="14" y="17" width="37" height="30" rx="7" fill="#7f9f97"/><path d="M5 28h9v9H5m46-10h8v10h-8M22 21v21m8-21v21m8-21v21"/>',
 phone:'<rect x="18" y="5" width="30" height="54" rx="5" fill="#727b70"/><path d="M22 13h22v32H22z" fill="#b4c7af"/><path d="m31 18-3 9 10 3-6 10M29 52h7"/>',
 chain:'<g fill="none" stroke-width="5"><ellipse cx="21" cy="22" rx="10" ry="15" transform="rotate(-30 21 22)"/><ellipse cx="39" cy="41" rx="10" ry="15" transform="rotate(-30 39 41)"/></g>',
 rope:'<path d="M12 13q39-10 37 16T17 43q-8-17 8-18t18 19l11 10" fill="none" stroke="#b79058" stroke-width="8"/>',
 magnet:'<path d="M12 13h12v25q8 12 16 0V13h12v28q-20 30-40 0z" fill="#c6684d"/><path d="M12 13h12v10H12m28-10h12v10H40" fill="#a9b7a8"/>',
 spring:'<path d="M19 9c40 4 40 15 3 13s-3 16 19 15-1 19-23 14M20 14c-15 5 0 14 21 14M23 35c-17 5-5 14 18 14" fill="none" stroke="#8b9989" stroke-width="4"/>',
 charger:'<rect x="13" y="20" width="31" height="28" rx="5" fill="#66786c"/><path d="M20 20V9m14 11V9m-5 39q0 14 19 7V40" fill="none" stroke-width="4"/>',
 rod:'<path d="m11 48 36-38 7 7-36 38z" fill="#a2ada0"/>',
 wood:'<path d="m7 29 42-15 9 24-42 15z" fill="#b88d55"/><path d="m14 33 31-11M21 43l29-10m-31 3 6-2" stroke="#8e653d"/>',
 bucket:'<path d="M13 23h38l-6 32H20z" fill="#b4a36d"/><path d="M15 26V16q17-21 34 0v10" fill="none"/><ellipse cx="32" cy="23" rx="19" ry="6" fill="#d5c78f"/>',
 cap:'<ellipse cx="32" cy="35" rx="23" ry="17" fill="#ba784b"/><ellipse cx="32" cy="29" rx="23" ry="17" fill="#e1aa5c"/><path d="m20 26 6 8 18-13" fill="none"/>',
 cloth:'<path d="m11 15 38 5 5 31-18-5-20 9-9-21z" fill="#8cad9c"/><path d="m15 20 4 24 15-6 15 6M29 21l-4 14" fill="none"/>',
 fuse:'<path d="m12 39 28-28 13 13-28 28z" fill="#c7d5bb"/><path d="m12 39 7 7 9-9m12-26 7 7-9 9M27 37l-2-7 11 1 1-7" fill="none"/>',
 torch:'<path d="m20 23 13-12 18 20-14 12z" fill="#e2b750"/><path d="m20 23 17 20-12 13-17-20z" fill="#718d7c"/><path d="m38 6 6-5m10 15 7-1"/>',
 switch:'<rect x="15" y="10" width="34" height="46" rx="4" fill="#d8ceae"/><path d="M23 21h18v24H23z" fill="#769385"/><path d="M23 29h18"/>',
 spoon:'<ellipse cx="40" cy="18" rx="11" ry="15" transform="rotate(35 40 18)" fill="#b0b8a5"/><path d="m33 30-19 24" stroke-width="7"/>'};
function icon(name){return `<svg viewBox="0 0 64 64" aria-hidden="true"><g stroke="#43594e" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">${shapes[name]||shapes.motor}</g></svg>`}
function machine(type){let inner='';if(type==='fan')inner='<path d="M76 78h9v47H76zM53 127q25-14 55 0v8H53z" fill="#688f82"/><circle cx="80" cy="52" r="42" fill="#aec1a5"/><g class="rotor"><path d="M80 52Q36 12 71 14q27-2 9 38Q121 7 120 42q0 27-40 10Q125 91 90 93q-27 1-10-41Q36 97 39 63q1-28 41-11" fill="#447768"/></g><circle cx="80" cy="52" r="39" fill="none"/><path d="M40 52h80M80 12v80M52 24l56 56M51 80l57-57" opacity=".35"/><circle cx="80" cy="52" r="8" fill="#e3ba65"/>';
else if(['scooter','bicycle','auto'].includes(type))inner=`<circle cx="34" cy="112" r="20" fill="#56665a"/><circle cx="128" cy="112" r="20" fill="#56665a"/><circle cx="34" cy="112" r="10" fill="#d8ca9f"/><circle cx="128" cy="112" r="10" fill="#d8ca9f"/><path d="M35 101h53l22-49h18l10 53H97L65 69H34z" fill="${type==='auto'?'#d2af50':'#b96747'}"/><path d="M41 65h32M110 53V41h-13" stroke-width="7"/>${type==='auto'?'<path d="M26 62V26h79l17 36z" fill="#729083"/><path d="M78 30h23l11 26H78z" fill="#d5ccaa"/>':''}`;
else if(type==='tank')inner='<path d="M30 34q50-25 100 0v86q-50 25-100 0z" fill="#83a8a5"/><ellipse cx="80" cy="34" rx="50" ry="13" fill="#adc5b4"/><path d="M32 57q48 21 96 0M32 93q48 21 96 0M107 77l-9 12 13 6-9 16" fill="none"/><path d="M113 117q-12 16 0 17q12-1 0-17" fill="#649dad"/>';
else inner=`<rect x="26" y="28" width="108" height="93" rx="8" fill="${type==='radio'?'#bd9365':'#8e9e88'}"/><rect x="36" y="40" width="88" height="59" rx="3" fill="#394f49"/>${type==='radio'?'<circle cx="65" cy="69" r="21" fill="#9ca886"/><path d="M98 49v37M107 49v37M115 49v37"/>':type==='cooler'?'<path d="M40 52h80M40 62h80M40 72h80M40 82h80" stroke="#b3c1a0"/>':'<path d="m60 66 10-8m-10 0 10 8m20-8 10 8m-10 0 10-8M69 84h23" stroke="#e2b763"/>'}<circle cx="113" cy="110" r="4" fill="#e4be5d"/><path d="M48 121v10m65-10v10" stroke-width="6"/>`;
return `<svg viewBox="0 0 160 145" aria-label="${type} awaiting repair"><g stroke="#3e594f" stroke-width="3" stroke-linejoin="round" stroke-linecap="round">${inner}</g></svg>`;}
function modal(html){document.querySelector('.page').inert=true;$('#overlay').innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-label="${phase==='result'?'Repair result':'Game menu'}">${html}</section>`;$('#overlay').querySelector('button')?.focus();}
function close(){returnScreen=null;document.querySelector('.page').inert=false;paused=false;$('#overlay').innerHTML='';last=performance.now();}
function updateSettings(){document.body.classList.toggle('reduced',!settings.motion);$('#sound').textContent=settings.sound?'♪':'♫̸';$('#sound').setAttribute('aria-label',settings.sound?'Mute sound':'Unmute sound')}
function stats(){const r=run||{money:120,rep:100,points:0,served:0,happy:0,round:1,earned:0};const l=levelFor(r.earned);$('#money').textContent=`₹${r.money}`;$('#rep').innerHTML=`${r.rep}<span>/100</span>`;$('#rep-bar').style.width=`${r.rep}%`;$('#points').textContent=r.points.toLocaleString();$('#served').textContent=`${r.served} served · ${r.happy} happy`;$('#day').textContent=`DAY ${String(Math.ceil(r.round/5)).padStart(2,'0')} / CUSTOMER ${String(r.round).padStart(2,'0')}`;$('#level').textContent=`LEVEL 0${l+1}`;$('#level-name').textContent=BALANCE.levelNames[l];$('#upgrade').textContent=l<4?`₹${BALANCE.levels[l+1]-r.earned} more earned → next upgrade`:'The lane is officially your laboratory.';$('#level-bar').style.width=l===4?'100%':`${100*(r.earned-BALANCE.levels[l])/(BALANCE.levels[l+1]-BALANCE.levels[l])}%`;$('#bench').className=`bench level-${l}`;$('#pedia-count').textContent=discoveries.length;$('#profit').textContent=r.money<0?'Running on credit and confidence.':'A little scrap goes a long way.'}
function renderJob(){if(!job)return;$('#order').textContent=`#${String(run?.round||1).padStart(3,'0')}`;$('#problem').textContent=job.problem.name;$('#fault').textContent=job.problem.fault;$('#machine').innerHTML=machine(job.problem.machine);$('#person').textContent=job.person[0];$('#dialogue').textContent=job.person[1];$('#scene').classList.remove('working','broken','success-flash');$('#customer').classList.remove('react');$('#scene-label').textContent='WAITING FOR YOUR BRIGHT IDEA';$('#event').className=`event ${job.event.id==='normal'?'':'chaos'}`;$('#event').innerHTML=`<span class="eyebrow">⚡ ON THE STREET</span><h3>${job.event.name}</h3><p>${job.event.desc}</p>`;$('#scrap-count').innerHTML=`${job.inventory.length}<br><small>FINDS</small>`;renderSelection();renderTimer();}
function renderSelection(){const items=selected.map(id=>ITEMS.find(i=>i.id===id)),tags=new Set(items.flatMap(i=>i.tags));$('#needs').innerHTML=job.problem.needs.map(n=>`<span class="tag ${tags.has(n)?'covered':''}">${n}</span>`).join('');$('#inventory').innerHTML=job.inventory.map(i=>`<button class="card ${selected.includes(i.id)?'selected':''}" data-id="${i.id}" draggable="${!selected.includes(i.id)}" aria-pressed="${selected.includes(i.id)}" aria-label="${i.name}: ${i.tags.join(', ')}. ${i.cost} rupees"><span class="price">₹${job.event.id==='truck'?0:Math.round(i.cost*(job.event.id==='crash'?.5:1))}</span>${icon(i.icon)}<span><b>${i.name}</b><small>${i.tags.join(' · ')}</small></span></button>`).join('');$('#slots').innerHTML=[0,1,2].map((n)=>{const i=items[n];return `<button class="slot ${i?'filled':'empty'}" data-slot="${n}" aria-label="${i?`Remove ${i.name}`:`Empty combination slot ${n+1}`}" ${i?'draggable="true"':''}>${i?`${icon(i.icon)}<span>${i.name}<small>${i.tags.join(' · ')}</small></span><span class="remove">×</span>`:`<span>＋</span><div>Slot 0${n+1}<small>${n===2?'OPTIONAL':'DROP SCRAP HERE'}</small></div>`}</button>`}).join('');$('#build').disabled=items.length<2||phase!=='playing';if(items.length>=2){const e=evaluate(job.problem,items,job.event);$('#preview').textContent=`${e.covered.length}/${job.problem.needs.length} needs covered · ₹${e.cost} parts${e.danger>45?' · ⚠ high danger':''}`;}else $('#preview').textContent='A little logic. A lot of jugaad.';}
function choose(id,slot=null){if(phase!=='playing'||paused)return;if(selected.includes(id)){if(slot===null)selected=selected.filter(x=>x!==id);else{const from=selected.indexOf(id);[selected[from],selected[Math.min(slot,selected.length-1)]]=[selected[Math.min(slot,selected.length-1)],selected[from]];}}else if(selected.length<3)selected.splice(slot===null?selected.length:Math.min(slot,selected.length),0,id);else if(slot!==null)selected[slot]=id;else{toast('Workbench full — tap an item in a slot to remove it.');return}sound('clang');renderSelection();persist()}
function newRun(){run={money:BALANCE.startingMoney,rep:BALANCE.startingRep,points:0,served:0,happy:0,round:1,earned:0,explosions:0,inspections:0,bestCombo:0};nextJob(false)}
function nextJob(increment=true){if(run.rep<=0){gameOver();return}if(increment)run.round++;job=makeRound(run.round);selected=[];remaining=job.time;phase='playing';close();stats();renderJob();sound('arrival');persist()}
function renderTimer(){$('#timer b').textContent=Math.max(0,Math.ceil(remaining));$('#timer').classList.toggle('urgent',remaining<10)}
function particles(good,count=25){if(!settings.motion)return;for(let i=0;i<count;i++){const p=document.createElement('i');p.className='particle';p.style.cssText=`left:${window.innerWidth*.45}px;top:${window.innerHeight*.4}px;--dx:${(Math.random()-.5)*650}px;--dy:${(Math.random()-.6)*450}px;background:${(good?['#efbd3f','#53967d','#ec724b']:['#e66235','#bcb493'])[i%(good?3:2)]}`;$('#fx').append(p);setTimeout(()=>p.remove(),1100)}}
function floating(text){const el=document.createElement('div');el.className='floating';el.textContent=text;$('#fx').append(el);setTimeout(()=>el.remove(),1600)}
function build(timeout=false){if(phase!=='playing'||paused||(!timeout&&selected.length<2))return;phase='result';const items=selected.map(id=>ITEMS.find(i=>i.id===id));const key=comboKey(items);const known=discoveries.some(d=>d.key===key&&d.problem===job.problem.name);const e=timeout?{works:false,score:0,money:0,rep:-BALANCE.timeoutPenalty,explosion:false,functionality:0,creativity:0,economy:0,safety:100,absurdity:0,danger:0}:evaluate(job.problem,items,job.event,known);const before=levelFor(run.earned);
run.money+=e.money;run.rep=Math.max(0,Math.min(100,run.rep+e.rep));run.points+=e.score;run.served++;run.happy+=Number(e.works);run.earned+=Math.max(0,e.money);run.explosions+=Number(e.explosion);run.inspections+=Number(job.event.id==='inspection');run.bestCombo=Math.max(run.bestCombo,e.score);best=Math.max(best,run.points);
const name=timeout?'The invisible repair':`${items.some(i=>i.id==='bottle')?'Bottle':items.some(i=>i.id==='brick')?'Brick':items[0].name.split(' ')[0]}-${e.works?'Turbo':'Dubious'} ${['3000','Deluxe','Express','Mark II'][run.round%4]}`;
const discovered=e.works&&!known;if(discovered){discoveries.unshift({key,name,problem:job.problem.name,items:items.map(i=>i.name),score:e.score});discoveries=discoveries.slice(0,100)}stats();renderSelection();persist();
$('#scene').classList.add(e.works?'working':'broken');if(e.works)$('#scene').classList.add('success-flash');$('#scene-label').textContent=e.works?'IT’S ALIVE. DO NOT ASK HOW.':'WELL, THAT WAS AN EXPERIMENT.';$('#dialogue').textContent=e.works?'I have questions. But it works!':'Is the smoke included in the price?';$('#customer').classList.add('react');if(e.explosion){document.body.classList.add('shake');setTimeout(()=>document.body.classList.remove('shake'),500);sound('spark')}else sound(e.works?'success':'fail');particles(e.works,e.score>=85?55:20);floating(`${e.money>=0?'+':''}₹${e.money}`);if(e.works)setTimeout(()=>sound('coins'),320);
const verdict=timeout?'Customer left. Patience is not a renewable resource.':e.works?(e.danger>45?'Questionable engineering. Somehow works.':'The laws of physics have reluctantly approved.'):(e.functionality>=65?'Almost brilliant. Unfortunately, “almost” does not spin a fan.':'An excellent modern-art installation. A terrible repair.');
setTimeout(()=>{if(phase!=='result')return;modal(`<span class="eyebrow">REPAIR ORDER #${String(run.round).padStart(3,'0')} / COMPLETE</span><h1 class="result-name">${name}</h1><span class="verdict ${e.works?'':'bad'}">${e.works?'IT WORKS!':timeout?'TIME’S UP':e.explosion?'SMALL EXPLOSION. BIG AMBITION.':'ABSOLUTELY QUESTIONABLE'}</span><p>${verdict}</p><div class="result-stats"><div>JUGAAD SCORE<b>${e.score}<small>/100</small></b></div><div>CASH CHANGE<b>${e.money>=0?'+':''}₹${e.money}</b></div><div>REPUTATION<b>${e.rep>=0?'+':''}${e.rep}</b></div></div><div class="breakdown">${[['Functionality',e.functionality],['Creativity',e.creativity],['Economy',e.economy],['Safety',e.safety],['Absurdity',e.absurdity]].map(([k,v])=>`<span>${k}<b>${v}</b></span>`).join('')}</div>${e.fine?'<p>Inspection fine: ₹25 and 8 reputation included.</p>':''}${discovered?'<div class="discovery">✦ NEW DISCOVERY — saved to your Jugaadpedia.</div>':''}${levelFor(run.earned)>before?`<div class="discovery">↑ SHOP UPGRADED: ${BALANCE.levelNames[levelFor(run.earned)]}</div>`:''}<div class="modal-actions"><button class="primary" id="next">${run.rep<=0?'CLOSE UP SHOP':'NEXT CUSTOMER'} ↗</button><span class="start-note">${timeout?'Try watching the patience timer.':!e.works?'Green property chips = needs covered.':'Another satisfied, slightly confused customer.'}</span></div>`);$('#next').onclick=()=>nextJob();if(levelFor(run.earned)>before)sound('level');},750);
}
function gameOver(){phase='over';persist();modal(`<span class="eyebrow">END OF AN EXTREMELY QUESTIONABLE ERA</span><h1>SHOP<br>SHUT DOWN.</h1><p>Your workshop survived ${run.served} customers, ${run.explosions} explosions and ${run.inspections} inspections. The neighbours will remember the noise.</p><div class="result-stats"><div>FINAL SCORE<b>${run.points}</b></div><div>BEST COMBO<b>${run.bestCombo}</b></div><div>CASH LEFT<b>₹${run.money}</b></div></div><p>Personal best: ${best} points. Your discoveries are safe.</p><div class="modal-actions"><button id="restart" class="primary">ANOTHER BRIGHT IDEA ↗</button><button id="back-home" class="secondary">Main menu</button></div>`);$('#restart').onclick=newRun;$('#back-home').onclick=()=>startScreen()}
function startScreen(){paused=true;const resumable=run&&run.rep>0&&phase!=='over';modal(`<span class="eyebrow">WELCOME TO GALI NO. 04</span><div class="hero-sign">JUGAAD<br><em>JUNCTION.</em></div><p>Anything can be fixed.<br>With the wrong parts and the right attitude.</p><div class="hazard"></div><p>Run a roadside repair stall. Turn random scrap into ridiculous inventions. Keep the customers — and your reputation — alive.</p><div class="modal-actions">${resumable?'<button class="primary" id="resume">CONTINUE SHIFT ↗</button><button class="secondary" id="new">New shift</button>':'<button class="primary" id="new">OPEN THE SHOP ↗</button>'}<button class="secondary" id="start-help">How to play</button></div><p class="start-note">2–3 PARTS. ONE BRIGHT IDEA. ZERO WARRANTIES.<br>BEST SHIFT: ${best} POINTS · ${discoveries.length} DISCOVERIES</p>`);$('#new').onclick=()=>{sound('click');newRun()};if($('#resume'))$('#resume').onclick=()=>{if(phase==='between'||phase==='result')nextJob();else{phase='playing';close();renderSelection();sound('click')}};$('#start-help').onclick=()=>showHelp(startScreen)}
function subMenu(content,back){paused=true;modal(content+'<div class="modal-actions"><button class="primary" id="close-modal">BACK ↗</button></div>');$('#close-modal').onclick=back;returnScreen=back;}
function safeBack(){if(phase==='playing')close();else if(phase==='over')gameOver();else startScreen()}
function showHelp(back=safeBack){subMenu('<span class="eyebrow">THE ART OF MAKING DO</span><h1>A little scrap.<br>A lot of possibility.</h1><ol class="instructions"><li>Read the repair’s required properties, such as <b>power + rotation + structural</b>.</li><li>Drag or tap <b>2–3 scrap cards</b> into the workbench. Covered properties turn green. Tap a slot to remove its item.</li><li>Hit <b>Build Jugaad</b> before patience runs out. Cover every required property to make it work.</li><li>Cheap, unusual and safe builds score more. Watch street events: rain, inspections and power cuts change the rules.</li><li>Earn cash to upgrade the stall. At zero reputation, the shop closes. Discoveries and your shift save automatically.</li></ol><p>Keys: 1–9 selects scrap, 0 selects the tenth item, Space builds, Escape pauses. Menus pause the clock.</p>',back)}
$('#inventory').onclick=e=>{const c=e.target.closest('[data-id]');if(c)choose(c.dataset.id)};$('#slots').onclick=e=>{const s=e.target.closest('[data-slot]');if(s&&selected[+s.dataset.slot])choose(selected[+s.dataset.slot])};
document.addEventListener('dragstart',e=>{if(paused||phase!=='playing'){e.preventDefault();return}const c=e.target.closest('[data-id]'),s=e.target.closest('[data-slot]');const id=c?.dataset.id||(s?selected[+s.dataset.slot]:null);if(id){e.dataTransfer.setData('text/plain',id);e.dataTransfer.effectAllowed='move'}});$('#slots').ondragover=e=>{e.preventDefault();e.target.closest('.slot')?.classList.add('dragover')};$('#slots').ondragleave=e=>e.target.closest('.slot')?.classList.remove('dragover');$('#slots').ondrop=e=>{e.preventDefault();const s=e.target.closest('[data-slot]'),id=e.dataTransfer.getData('text/plain');if(s&&job.inventory.some(i=>i.id===id))choose(id,+s.dataset.slot)};
$('#build').onclick=()=>build();$('#sound').onclick=()=>{settings.sound=!settings.sound;updateSettings();sound('click');persist()};$('#help').onclick=()=>{if(phase!=='result')showHelp()};$('#home').onclick=e=>{e.preventDefault();if(phase!=='result')startScreen()};$('#pedia').onclick=()=>{if(phase==='result')return;subMenu(`<span class="eyebrow">THE UNOFFICIAL PATENT OFFICE</span><h1>Jugaadpedia</h1><p>${discoveries.length} inventions that probably should not work.</p>${discoveries.length?discoveries.map(d=>`<div class="pedia-entry"><b>${d.name} <span style="color:var(--orange)">${d.score} pts</span></b><p>${d.items.join(' + ')}</p><p>Fixed: ${d.problem}</p></div>`).join(''):'<p>Your first successful repair will appear here. Experiment with different combinations to fill the book.</p>'}`,safeBack)};
$('#settings').onclick=()=>{if(phase==='result')return;subMenu(`<span class="eyebrow">WORKSHOP PREFERENCES</span><h1>Settings</h1><label class="setting-row">Procedural sound effects<input type="checkbox" id="setting-sound" ${settings.sound?'checked':''}></label><label class="setting-row">Animations & particles<input type="checkbox" id="setting-motion" ${settings.motion?'checked':''}></label><p>${storageOK?'Progress is saved automatically in this browser.':'Browser storage is unavailable for this session.'}</p>`,safeBack);$('#setting-sound').onchange=e=>{settings.sound=e.target.checked;updateSettings();persist()};$('#setting-motion').onchange=e=>{settings.motion=e.target.checked;updateSettings();persist()}};
function pause(){if(phase!=='playing')return;if(paused){safeBack();return}paused=true;modal('<span class="eyebrow">CHAI BREAK</span><h1>Tools down.</h1><p>The customers can wait. Your clock is paused.</p><div class="modal-actions"><button class="primary" id="unpause">BACK TO WORK ↗</button><button class="secondary" id="pause-menu">Main menu</button></div>');$('#unpause').onclick=close;$('#pause-menu').onclick=startScreen;persist()}
$('#pause').onclick=pause;document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();if(paused&&returnScreen){const back=returnScreen;returnScreen=null;back()}else pause()}if(phase==='playing'&&!paused){if(e.code==='Space'){e.preventDefault();build()}if(/^[0-9]$/.test(e.key)){const i=job.inventory[e.key==='0'?9:Number(e.key)-1];if(i)choose(i.id)}}});
// Pointer dragging works with mice, pens and touch without native HTML drag quirks.
let drag=null,suppressClick=false;
document.addEventListener('dragstart',e=>e.preventDefault(),true);
document.addEventListener('pointerdown',e=>{if(phase!=='playing'||paused||e.button!==0)return;const card=e.target.closest('[data-id]'),slot=e.target.closest('[data-slot]');const id=card?.dataset.id||(slot?selected[+slot.dataset.slot]:null);if(id)drag={id,x:e.clientX,y:e.clientY,active:false,ghost:null};});
document.addEventListener('pointermove',e=>{if(!drag)return;if(!drag.active&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>7){drag.active=true;drag.ghost=document.createElement('div');drag.ghost.className='drag-ghost';const i=ITEMS.find(i=>i.id===drag.id);drag.ghost.innerHTML=icon(i.icon)+`<b>${i.name}</b>`;document.body.append(drag.ghost);}if(drag.active){e.preventDefault();drag.ghost.style.left=`${e.clientX+12}px`;drag.ghost.style.top=`${e.clientY+12}px`;document.querySelectorAll('.dragover').forEach(el=>el.classList.remove('dragover'));document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]')?.classList.add('dragover');}},{passive:false});
document.addEventListener('pointerup',e=>{if(!drag)return;const current=drag;drag=null;current.ghost?.remove();document.querySelectorAll('.dragover').forEach(el=>el.classList.remove('dragover'));if(current.active){suppressClick=true;setTimeout(()=>suppressClick=false,50);const slot=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');if(slot)choose(current.id,+slot.dataset.slot);}});
document.addEventListener('pointercancel',()=>{drag?.ghost?.remove();drag=null;document.querySelectorAll('.dragover').forEach(el=>el.classList.remove('dragover'));});
document.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();suppressClick=false;}},true);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&phase==='playing'&&!paused)pause()});window.addEventListener('beforeunload',persist);let saveClock=0;function tick(now){const dt=Math.min(1,(now-last)/1000);last=now;if(phase==='playing'&&!paused){remaining=Math.max(0,remaining-dt);renderTimer();saveClock+=dt;if(saveClock>2){persist();saveClock=0}if(remaining<=0)build(true)}requestAnimationFrame(tick)}
if(saved.run&&saved.job&&saved.run.rep>0&&['playing','between','result'].includes(saved.phase)&&Array.isArray(saved.job.inventory)&&saved.job.inventory.every(i=>ITEMS.some(v=>v.id===i.id))){run=saved.run;job=saved.job;selected=(saved.selected||[]).filter(id=>job.inventory.some(i=>i.id===id)).slice(0,3);remaining=Math.max(0,Number(saved.remaining)||0);phase=saved.phase==='result'?'between':saved.phase;}else{job=makeRound(1)}updateSettings();stats();renderJob();startScreen();requestAnimationFrame(tick);

